# Generated by Django 3.2 on 2024-01-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0031_alter_template_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModifiedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=32)),
                ('modified_on', models.DateField(auto_now=True)),
                ('role', models.CharField(max_length=32)),
                ('project_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
    ]
