# Generated by Django 3.2 on 2024-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0032_auto_20240125_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AlterField(
            model_name='projectmodifieddetails',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
