# Generated by Django 3.2 on 2024-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0037_alter_note_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AlterField(
            model_name='projectmodifieddetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
