# Generated by Django 3.2 on 2024-02-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0038_auto_20240201_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
    ]
