from django.db import models

class HailTest(models.Model):
    location = models.CharField(max_length=32, blank=True, null=True)
    date_time = models.DateTimeField(null=True, blank=True)
    operator = models.CharField(max_length=32, blank=True, null=True)
    customer_id = models.IntegerField(null=True,blank=True)
    project_id = models.IntegerField(null=True,blank=True)
    workorder_id = models.IntegerField(null=True,blank=True)
    test_sequence_id = models.IntegerField(null=True,blank=True)
    character_point_procedure = models.CharField(max_length=32, blank=True, null=True)
    unit = models.ForeignKey('Unit',on_delete=models.CASCADE, blank=True, null=True)
    mass_of_hail = models.FloatField(blank=True, null=True)
    flex_tip_mass = models.FloatField(blank=True, null=True)
    diameter = models.FloatField(blank=True, null=True)
    target_speed =  models.FloatField(blank=True, null=True)
    measured_speed = models.FloatField(blank=True, null=True)
    units_chosen_for_speed_suggested_pressure = models.FloatField(blank=True, null=True)
    target_pressure = models.FloatField(blank=True, null=True)
    actual_pressure = models.FloatField(blank=True, null=True)
    speed_in_range = models.FloatField(blank=True, null=True)
    module_angle = models.FloatField(blank=True, null=True)
    energy = models.FloatField(blank=True, null=True)
    time = models.IntegerField(null=True,blank=True)
    result_comments = models.CharField(max_length=125, blank=True, null=True)